#############################################################################
# Makefile for building: PhysX
# Generated by qmake (2.01a) (Qt 4.7.4) on: po 9. ?vc 18:19:59 2018
# Project:  PhysX.pro
# Template: app
# Command: c:\qtsdk\symbian\sdks\symbian3qt474\bin\qmake.exe -spec ..\..\..\..\QtSDK\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 QMLJSDEBUGGER_PATH=C:/QtSDK/Symbian/SDKs/Symbian3Qt474//qtc-qmldbg -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o bld.inf PhysX.pro
#############################################################################

MAKEFILE          = Makefile
QMAKE             = c:\qtsdk\symbian\sdks\symbian3qt474\bin\qmake.exe
DEL_FILE          = del /q 2> NUL
DEL_DIR           = rmdir
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
MOVE              = move
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make
SBS               = sbs

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH	 =  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/include/QtCore"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/include/QtGui"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/include/QtOpenGL"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/include"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/mkspecs/common/symbian"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/stdapis"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/stdapis/sys"  -I"C:/Projects/Qt/PhysX/PhysX_3.4/include"  -I"C:/Projects/Qt/PhysX/PxShared/include"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/stdapis/stlportv5"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/mw"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/mw"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/loc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/mw/loc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/loc/sc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/mw/loc/sc"  -I"C:/Projects/Qt/PhysX/Samples/moc"  -I"C:/Projects/Qt/PhysX/Samples/src"  -I"C:/Projects/Qt/PhysX/Samples/rcc"  -I"C:/Projects/Qt/PhysX/Samples/ui" 
first: default

all: debug release

default: debug-winscw
qmake:
	$(QMAKE) "C:/Projects/Qt/PhysX/Samples/PhysX.pro"  -spec ..\..\..\..\QtSDK\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 QMLJSDEBUGGER_PATH=C:/QtSDK/Symbian/SDKs/Symbian3Qt474//qtc-qmldbg -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

bld.inf: C:/Projects/Qt/PhysX/Samples/PhysX.pro
	$(QMAKE) "C:/Projects/Qt/PhysX/Samples/PhysX.pro"  -spec ..\..\..\..\QtSDK\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 QMLJSDEBUGGER_PATH=C:/QtSDK/Symbian/SDKs/Symbian3Qt474//qtc-qmldbg -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

c:\Projects\Qt\PhysX\Samples\PhysX.loc: 
	$(QMAKE) "C:/Projects/Qt/PhysX/Samples/PhysX.pro"  -spec ..\..\..\..\QtSDK\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 QMLJSDEBUGGER_PATH=C:/QtSDK/Symbian/SDKs/Symbian3Qt474//qtc-qmldbg -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

debug: c:\Projects\Qt\PhysX\Samples\PhysX.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
clean-debug: bld.inf
	$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
freeze-debug: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
release: c:\Projects\Qt\PhysX\Samples\PhysX.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
clean-release: bld.inf
	$(SBS) reallyclean --toolcheck=off -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
freeze-release: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

debug-winscw: c:\Projects\Qt\PhysX\Samples\PhysX.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc
clean-debug-winscw: bld.inf
	$(SBS) reallyclean -c winscw_udeb.mwccinc
freeze-debug-winscw: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc
debug-gcce: c:\Projects\Qt\PhysX\Samples\PhysX.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1_custom --configpath=%cd%/configs
clean-debug-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-gcce: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
debug-armv5: c:\Projects\Qt\PhysX\Samples\PhysX.loc bld.inf
	$(SBS) -c armv5_udeb
clean-debug-armv5: bld.inf
	$(SBS) reallyclean -c armv5_udeb
freeze-debug-armv5: bld.inf
	$(SBS) freeze -c armv5_udeb
debug-armv6: c:\Projects\Qt\PhysX\Samples\PhysX.loc bld.inf
	$(SBS) -c armv6_udeb
clean-debug-armv6: bld.inf
	$(SBS) reallyclean -c armv6_udeb
freeze-debug-armv6: bld.inf
	$(SBS) freeze -c armv6_udeb
release-gcce: c:\Projects\Qt\PhysX\Samples\PhysX.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-gcce: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
release-armv5: c:\Projects\Qt\PhysX\Samples\PhysX.loc bld.inf
	$(SBS) -c armv5_urel
clean-release-armv5: bld.inf
	$(SBS) reallyclean -c armv5_urel
freeze-release-armv5: bld.inf
	$(SBS) freeze -c armv5_urel
release-armv6: c:\Projects\Qt\PhysX\Samples\PhysX.loc bld.inf
	$(SBS) -c armv6_urel
clean-release-armv6: bld.inf
	$(SBS) reallyclean -c armv6_urel
freeze-release-armv6: bld.inf
	$(SBS) freeze -c armv6_urel
debug-armv5-gcce4.4.1: c:\Projects\Qt\PhysX\Samples\PhysX.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
release-armv5-gcce4.4.1: c:\Projects\Qt\PhysX\Samples\PhysX.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
debug-armv6-gcce4.4.1: c:\Projects\Qt\PhysX\Samples\PhysX.loc bld.inf
	$(SBS) -c arm.v6.udeb.gcce4_4_1
clean-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.gcce4_4_1
freeze-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.udeb.gcce4_4_1
release-armv6-gcce4.4.1: c:\Projects\Qt\PhysX\Samples\PhysX.loc bld.inf
	$(SBS) -c arm.v6.urel.gcce4_4_1
clean-release-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.gcce4_4_1
freeze-release-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.urel.gcce4_4_1

export: bld.inf
	$(SBS) export -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

cleanexport: bld.inf
	$(SBS) cleanexport -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

freeze: freeze-release

check: first

run:
	call C:/QtSDK/Symbian/SDKs/Symbian3Qt474/epoc32/release/winscw/udeb/PhysX.exe $(QT_RUN_OPTIONS)

runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis PhysX.sis PhysX.exe $(QT_RUN_OPTIONS)

PhysX_template.pkg: C:/Projects/Qt/PhysX/Samples/PhysX.pro
	$(MAKE) -f $(MAKEFILE) qmake

PhysX_installer.pkg: C:/Projects/Qt/PhysX/Samples/PhysX.pro
	$(MAKE) -f $(MAKEFILE) qmake

PhysX_stub.pkg: C:/Projects/Qt/PhysX/Samples/PhysX.pro
	$(MAKE) -f $(MAKEFILE) qmake

sis: PhysX_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_sis:
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) PhysX_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_sis: PhysX_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_unsigned_sis:
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) -o PhysX_template.pkg $(QT_SIS_TARGET)

PhysX.sis:
	$(MAKE) -f $(MAKEFILE) sis

installer_sis: PhysX_installer.pkg sis
	$(MAKE) -f $(MAKEFILE) ok_installer_sis

ok_installer_sis: PhysX_installer.pkg
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) PhysX_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_installer_sis: PhysX_installer.pkg unsigned_sis
	$(MAKE) -f $(MAKEFILE) ok_unsigned_installer_sis

ok_unsigned_installer_sis: PhysX_installer.pkg
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) -o PhysX_installer.pkg

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

stub_sis: PhysX_stub.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_stub_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_stub_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_stub_sis:
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat -s $(QT_SIS_OPTIONS) PhysX_stub.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

deploy: sis
	call PhysX.sis

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc\moc_GlWidget.cpp moc\moc_SampleBase.cpp moc\moc_Sample00.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc\moc_GlWidget.cpp moc\moc_SampleBase.cpp moc\moc_Sample00.cpp
moc\moc_GlWidget.cpp: src\ISceneObjectProvider.h \
		src\GlWidget.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Projects\Qt\PhysX\Samples\src\GlWidget.h -o c:\Projects\Qt\PhysX\Samples\moc\moc_GlWidget.cpp

moc\moc_SampleBase.cpp: src\ISceneObjectProvider.h \
		src\SampleBase.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Projects\Qt\PhysX\Samples\src\SampleBase.h -o c:\Projects\Qt\PhysX\Samples\moc\moc_SampleBase.cpp

moc\moc_Sample00.cpp: src\SampleBase.h \
		src\ISceneObjectProvider.h \
		src\Sample00.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Projects\Qt\PhysX\Samples\src\Sample00.h -o c:\Projects\Qt\PhysX\Samples\moc\moc_Sample00.cpp

compiler_rcc_make_all: rcc\qrc_qresources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc\qrc_qresources.cpp
rcc\qrc_qresources.cpp: qrc\qresources.qrc \
		images\logo.png
	c:\QtSDK\Symbian\SDKs\Symbian3Qt474\bin\rcc.exe -name qresources c:\Projects\Qt\PhysX\Samples\qrc\qresources.qrc -o c:\Projects\Qt\PhysX\Samples\rcc\qrc_qresources.cpp

compiler_image_collection_make_all: ui\qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui\qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

dodistclean:
	-@ if EXIST "c:\Projects\Qt\PhysX\Samples\PhysX_template.pkg" $(DEL_FILE)  "c:\Projects\Qt\PhysX\Samples\PhysX_template.pkg"
	-@ if EXIST "c:\Projects\Qt\PhysX\Samples\PhysX_stub.pkg" $(DEL_FILE)  "c:\Projects\Qt\PhysX\Samples\PhysX_stub.pkg"
	-@ if EXIST "c:\Projects\Qt\PhysX\Samples\PhysX_installer.pkg" $(DEL_FILE)  "c:\Projects\Qt\PhysX\Samples\PhysX_installer.pkg"
	-@ if EXIST "c:\Projects\Qt\PhysX\Samples\Makefile" $(DEL_FILE)  "c:\Projects\Qt\PhysX\Samples\Makefile"
	-@ if EXIST "c:\Projects\Qt\PhysX\Samples\PhysX_exe.mmp" $(DEL_FILE)  "c:\Projects\Qt\PhysX\Samples\PhysX_exe.mmp"
	-@ if EXIST "c:\Projects\Qt\PhysX\Samples\PhysX_reg.rss" $(DEL_FILE)  "c:\Projects\Qt\PhysX\Samples\PhysX_reg.rss"
	-@ if EXIST "c:\Projects\Qt\PhysX\Samples\PhysX.rss" $(DEL_FILE)  "c:\Projects\Qt\PhysX\Samples\PhysX.rss"
	-@ if EXIST "c:\Projects\Qt\PhysX\Samples\PhysX.loc" $(DEL_FILE)  "c:\Projects\Qt\PhysX\Samples\PhysX.loc"
	-@ if EXIST "c:\Projects\Qt\PhysX\Samples\bld.inf" $(DEL_FILE)  "c:\Projects\Qt\PhysX\Samples\bld.inf"

distclean: clean dodistclean

clean: bld.inf
	-$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1


